version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        tests:            
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
        identifier: raw_gz_sales
        description: sales made by greenweez, one row per product found in each order_id
      - name: product
        columns: 
          - name: products_id
            tests: 
              - unique
              - not_null
        identifier: raw_gz_product
        description: price for each product, one row per product_id
      - name: ship
        columns: 
          - name: orders_id
            tests: 
              - unique 
              - not_null 
        identifier: raw_gz_ship
        description: shipping cost per order, one row per order_id
      - name: adword
        identifier: raw_gz_adwords
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
      - name: bing
        identifier: raw_gz_bing
      - name: int_campaigns
        tests:            
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
        identifier: int_campaigns
        description:  all ads sources in a single table
      - name: int_campaigns_days
        columns: 
            - name: date_date
              tests: 
                - unique 
                - not_null 
        identifier: int_campaigns_days
        description: aggergation of all ads sources in a single table, aggregated by day
      - name: finance_campaigns_day
        columns: 
            - name: date_date
              tests: 
                - unique 
                - not_null 
        identifier: finance_campaigns_day
        description: finance day table with ads margin included, aggregated by day